<?xml version="1.0"?>
<robot name="human" xmlns:xacro="http://www.ros.org/wiki/xacro" >
<!--
Robot model taken from http://wiki.ros.org/pr2_mechanism/Tutorials/SImple%20URDF-Controller%20Example
-->
  <xacro:include filename="$(find human_model_gazebo)/urdf/wheel.xacro"/>

  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="human_back_length" value="0.5" /> 
  <xacro:property name="length" value="0.4" /> 
  <xacro:property name="width" value="0.4" /> 
  <xacro:property name="wheel_radius" value="0.11" /> <!-- Link 1 -->
  <xacro:property name="thickness" value="0.086" /> <!-- Link 2 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="steer_offset" value="0.02" /> <!-- Link 1 -->
  <xacro:property name="steer_height" value="0.4" />
  <xacro:property name="board_length" value="0.8" />
  <xacro:property name="board_width" value="0.3" /> 

  <material name="white">
    <color rgba="0.45 0.45 0.45 1"/>
  </material>

  <material name="wood">
    <color rgba="0.54509 0.2705 0.0745 1"/>
  </material>

  <material name="black">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="green">
    <color rgba="0.95 0.95 0.95 1"/>
  </material>

  <material name="pink">
    <color rgba="1 0.4 1 1"/>
  </material>

   <material name="orange">
    <color rgba="0 1 1 1"/>
  </material>

   <material name="blue">
    <color rgba="0 0 1 0.5"/>
  </material>

  <!-- Links: inertial,visual,collision -->
  <link name="base_human_link">
    <!-- <inertial>
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial> -->
    <visual>
      <geometry>
        <box size="${length} ${width} 0.04"/>
      </geometry>
      <material name="wood"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.04"/>
      </geometry>
    </collision>
  </link>

  <link name="base_footprint">
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00000001"/>
      </geometry>
      <material name="white"/>
    </collision>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    <parent link="base_human_link"/>
    <child link="base_footprint"/>
  </joint>

  <!-- Links: inertial,visual,collision -->
  <link name="back_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${human_back_length} ${width} 0.04"/>
      </geometry>
      <material name="wood"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.04"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_back_joint" type="fixed">
      <origin xyz="${-length/2.0 + 0.02} 0 ${length/2.0}" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="back_link"/>
    <parent link="base_human_link"/>
  </joint>

 <!-- -->


  <!-- Wheels -->
  <front_wheel name="front_right" parent="base_human" radius="${wheel_radius}" thickness="${thickness}" 
      length="${length}" width="${width}" axel_offset="${axel_offset}" right_left="1" steer_height="${steer_height}">
  </front_wheel>
  <front_wheel name="front_left" parent="base_human" radius="${wheel_radius}" thickness="${thickness}" 
      length="${length}" width="${width}" axel_offset="${axel_offset}" right_left="-1" steer_height="${steer_height}">
  </front_wheel>
  <rear_wheel name="rear_right" parent="base_human" radius="${wheel_radius}" thickness="${thickness}" 
      length="${length}" width="${width}" axel_offset="${axel_offset}" right_left="1" steer_height="${steer_height}">
  </rear_wheel>
  <rear_wheel name="rear_left" parent="base_human" radius="${wheel_radius}" thickness="${thickness}" 
      length="${length}" width="${width}" axel_offset="${axel_offset}" right_left="-1" steer_height="${steer_height}">
  </rear_wheel>

  <!-- Links: inertial,visual,collision -->
  <link name="body_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${human_back_length} 0.25 0.1"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${human_back_length} 0.25 0.1"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_body_joint" type="fixed">
      <origin xyz="-0.0 0 ${human_back_length/2.0}" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="body_link"/>
    <parent link="base_human_link"/>
  </joint>

  <link name="bodyright_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>

    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="${human_back_length}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="${human_back_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="body_bodyright_joint" type="fixed">
    <origin xyz="0.0 -0.125 0" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="bodyright_link"/>
    <parent link="body_link"/>
    
  </joint>

  <!-- left leg -->
  <link name="bodyleft_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="${human_back_length}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="${human_back_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="body_bodyleft_joint" type="fixed">
      <origin xyz="0.0 0.125 0" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="bodyleft_link"/>
    <parent link="body_link"/>
  </joint>
  <link name="legright1_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
       <cylinder radius="0.05" length="0.25"/>
      </geometry>
    </collision>
  </link>
  <joint name="bodyright_legright1_joint" type="fixed">
      <origin xyz="-0.2 0 ${human_back_length/2-0.075}" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="legright1_link"/>
    <parent link="bodyright_link"/>
  </joint>

  <link name="legleft1_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
    </collision>
  </link>
  <joint name="bodyleft_legleft1_joint" type="fixed">
      <origin xyz="-0.2 0 ${human_back_length/2-0.075}" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="legleft1_link"/>
    <parent link="bodyleft_link"/>
  </joint>

  <link name="legright2_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="legright1_legright2_joint" type="fixed">
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
    <child link="legright2_link"/>
    <parent link="legright1_link"/>
  </joint>

  <link name="legleft2_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="legleft1_legleft2_joint" type="fixed">
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
    <child link="legleft2_link"/>
    <parent link="legleft1_link"/>
  </joint>

  <link name="legleft3_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.45"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.45"/>
      </geometry>
    </collision>
  </link>
  <joint name="legleft2_legleft3_joint" type="fixed">
      <origin xyz="0.225 0 0" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="legleft3_link"/>
    <parent link="legleft2_link"/>
  </joint>

  <link name="legright3_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.45"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.45"/>
      </geometry>
    </collision>
  </link>
  <joint name="legright2_legright3_joint" type="fixed">
      <origin xyz="0.225 0 0" rpy="0 ${-90 * deg_to_rad} 0"/>
    <child link="legright3_link"/>
    <parent link="legright2_link"/>
  </joint>

  <link name="footleft_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.2 0.1 0.08"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="0.2 0.1 0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="legleft3_footleft_joint" type="fixed">
      <origin xyz="0.05 0 -${0.45*0.5}" rpy="0 0 0"/>
    <child link="footleft_link"/>
    <parent link="legleft3_link"/>
  </joint>

  <link name="footright_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.2 0.1 0.08"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="0.2 0.1 0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="legrihgt3_footrihgt_joint" type="fixed">
      <origin xyz="0.05 0 -${0.45*0.5}" rpy="0 0 0"/>
    <child link="footright_link"/>
    <parent link="legright3_link"/>
  </joint>

  <!-- Chest -->
  <link name="chest_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
    </collision>
  </link>
  <joint name="body_chest_joint" type="fixed">
      <origin xyz="0.25 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
    <child link="chest_link"/>
    <parent link="body_link"/>
  </joint>

  <!-- Head -->
  <link name="head_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.125"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.125"/>
      </geometry>
    </collision>
  </link>
  <joint name="chest_head_joint" type="fixed">
      <origin xyz="0.15 0 0" rpy="0 0 0"/>
    <child link="head_link"/>
    <parent link="chest_link"/>
  </joint>

  <!-- Arm -->
  <link name="shoulderleft_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="bodyleft_shoulderleft_joint" type="fixed">
      <origin xyz="0 0 -0.25" rpy="0 0 0"/>
    <child link="shoulderleft_link"/>
    <parent link="bodyleft_link"/>
  </joint>

  <link name="shoulderright_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="green"/>
    </visual>
    <material name="green"/>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="bodyright_shoulderright_joint" type="revolute">
      <origin xyz="0 0 -0.25" rpy="0 0 0"/>
    <child link="shoulderright_link"/>
    <parent link="bodyright_link"/>

     <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-0.6" upper="0.6" velocity="0.5"/>
  </joint>

  <link name="armright1_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
    </collision>
  </link>
  <!-- attempting to move the whole arm-->
  <joint name="shoulderright_armright1_joint" type="revolute"> 
    <origin xyz="-0.065 0 0.11" rpy="0 ${-30 * deg_to_rad} 0"/>
    <child link="armright1_link"/>
    <parent link="shoulderright_link"/>

    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-0.6" upper="0.6" velocity="0.5"/>
    <!-- <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" /> -->
  </joint>

  <link name="armleft1_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.25"/>
      </geometry>
    </collision>
  </link>
  <joint name="shoulderleft_armleft1_joint" type="fixed">
      <origin xyz="-0.065 0 0.11" rpy="0 ${-30 * deg_to_rad} 0"/>
    <child link="armleft1_link"/>
    <parent link="shoulderleft_link"/>
  </joint>

  <link name="armright2_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="armright1_armright2_joint" type="revolute">
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
    <child link="armright2_link"/>
    <parent link="armright1_link"/>

    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-0.6" upper="0.6" velocity="0.5"/>
  </joint>

  <link name="armleft2_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="armleft1_armleft2_joint" type="fixed">
      <origin xyz="0 0 0.125" rpy="0 0 0"/>
    <child link="armleft2_link"/>
    <parent link="armleft1_link"/>
  </joint>

  <link name="armleft3_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.2"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.2"/>
      </geometry>
    </collision>
  </link>
  <joint name="armleft2_armleft3_joint" type="fixed"> <!--if we want the left arm -->
      <axis xyz="1 1 0"/>
      <limit effort="1000.0" lower="-0.18" upper="0.18" velocity="0.5"/>
      <origin xyz="-0.065 0 0.11" rpy="0 ${-30 * deg_to_rad} 0"/>

    <child link="armleft3_link"/>
    <parent link="armleft2_link"/>
  </joint>

  <link name="armright3_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.2"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.2"/>
      </geometry>
    </collision>
  </link>
  <joint name="armright2_armright3_joint" type="fixed"> <!-- move from elbow down -->
      <axis xyz="1 1 1"/>
      <limit effort="1000.0" lower="-0.6" upper="0.6" velocity="0.5"/>
      <origin xyz="-0.065 0 0.11" rpy="0 ${-30 * deg_to_rad} 0"/>
    <child link="armright3_link"/>
    <parent link="armright2_link"/>
  </joint>

  <link name="handright_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
    </collision>
  </link>
  <joint name="armrighht3_handright_joint" type="revolute">
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
      <origin xyz="0 0 ${0.2*0.5}" rpy="0 0 0"/>
    <child link="handright_link"/>
    <parent link="armright3_link"/>
  </joint>

  <link name="handleft_link">
    <inertial>
      <!-- origin is relative -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <!-- <visual>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
      <material name="white"/>
    </visual> -->
    <collision>
      <!-- origin is relative -->
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.065"/>
      </geometry>
    </collision>
  </link>
  <joint name="armleft3_handleft_joint" type="fixed"> <!--in case we want the left arm-->
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" lower="0.0" upper="3.14" velocity="0.5"/>
      <origin xyz="0 0 ${0.2*0.5}" rpy="0 0 0"/>
    <child link="handleft_link"/>
    <parent link="armleft3_link"/>
  </joint>


  <!-- ==== Appending a right hand ======= -->
  <!-- <link name="root" /> -->
  <link name="base_0" />

  <link name="base">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_0.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_meta_0">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_1.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_meta" />

<link name="pinky_proximal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_2.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_middle">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_3.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_distal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_4.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_meta_0">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_6.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_meta" />

<link name="ring_proximal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_7.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_middle">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_8.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_distal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_9.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_meta_0">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_11.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_meta"/>

<link name="middle_proximal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_12.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_middle">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_13.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_distal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_14.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_meta_0">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_16.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_meta" />

<link name="index_proximal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_17.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_middle">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_18.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_distal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_19.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="thumb_meta_0" />

<link name="thumb_meta">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_21.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>  

<link name="thumb_proximal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_22.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="thumb_distal">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_0_23.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<joint name="wr_j0" type="fixed"> <!--"continuous" -->
  <parent link="handright_link"/>
  <child link="base_0"/>
  <origin xyz="0 0 0" rpy="0 0 -3.14" />
  <axis xyz="0 1 0" />
</joint>

<joint name="wr_j1" type="fixed"> <!--"continuous" -->
  <parent link="base_0"/>
  <child link="base"/>
  <origin xyz="0 0 0" rpy="1.57 0 0" />
  <axis xyz="1 0 0"  />
</joint>

<joint name="base_pinky" type="fixed">
  <parent link="base"/>
  <child link="pinky_meta_0"/>
  <origin xyz="-0.024912 0.008636 0.002422" rpy="2.80824 -0.811484 -2.74123" />
</joint>

<joint name="pi_j0" type="fixed"> <!--"continuous" -->
  <parent link="pinky_meta_0"/>
  <child link="pinky_meta"/>
  <origin xyz="0.000000 0.063265 -0.000000" rpy="0.0196487 -0.191181 0.113497" />
  <axis xyz="0 0 1" />
</joint>

<joint name="pi_j1" type="fixed"> <!--"continuous" -->
  <parent link="pinky_meta"/>
  <child link="pinky_proximal"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="pi_j2" type="fixed"> <!--"continuous" -->
  <parent link="pinky_proximal"/>
  <child link="pinky_middle"/>
  <origin xyz="0.000000 0.034557 0.000000" rpy="0.0304249 -0.0981504 0.133914" />
  <axis xyz="1 0 0" />
</joint>

<joint name="pi_j3" type="fixed"> <!--"continuous" -->
  <parent link="pinky_middle"/>
  <child link="pinky_distal"/>
  <origin xyz="0.000000 0.025298 -0.000000" rpy="-0.0317568 0.00503542 0.0988644" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_ring" type="fixed"> <!--"continuous" -->
  <parent link="base"/>
  <child link="ring_meta_0"/>
  <origin xyz="-0.012468 0.014241 -0.007279" rpy="3.03476 -0.620396 -2.98236" />
</joint>

<joint name="ri_j0" type="fixed"> <!--"continuous" -->
  <parent link="ring_meta_0"/>
  <child link="ring_meta"/>
    <origin xyz="0.000000 0.069086 -0.000000" rpy="-0.153666 -0.161247 0.0107861" />
  <axis xyz="0 0 1" />
</joint>

<joint name="ri_j1" type="fixed"> <!--"continuous" -->
  <parent link="ring_meta"/>
  <child link="ring_proximal"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="ri_j2" type="fixed"> <!--"continuous" -->
  <parent link="ring_proximal"/>
  <child link="ring_middle"/>
  <origin xyz="-0.000000 0.042662 -0.000000" rpy="0.0661994 0.10508 -0.0317381" />
  <axis xyz="1 0 0" />
</joint>

<joint name="ri_j3" type="fixed"> <!--"continuous" -->
  <parent link="ring_middle"/>
  <child link="ring_distal"/>
  <origin xyz="0.000000 0.028928 0.000000" rpy="0.102201 -0.0505654 0.0213048" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_middle" type="fixed">
  <parent link="base"/>
  <child link="middle_meta_0"/>
  <origin xyz="0.001406 0.015512 -0.015156" rpy="3.13273 -0.39616 -3.08577" />
</joint>

<joint name="mi_j0" type="fixed"> <!--"continuous" -->
  <parent link="middle_meta_0"/>
  <child link="middle_meta"/>
  <origin xyz="0.000000 0.073864 -0.000000" rpy="-0.182864 0.0762588 -0.0585634" />
  <axis xyz="0 0 1" />
</joint>

<joint name="mi_j1" type="fixed"> <!--"continuous" -->
  <parent link="middle_meta"/>
  <child link="middle_proximal"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="mi_j2" type="fixed"> <!--"continuous" -->
  <parent link="middle_proximal"/>
  <child link="middle_middle"/>
  <origin xyz="0.000000 0.047566 -0.000000" rpy="0.109335 -0.0553835 -0.0593373" />
  <axis xyz="1 0 0" />
</joint>

<joint name="mi_j3" type="fixed"> <!--"continuous" -->
  <parent link="middle_middle"/>
  <child link="middle_distal"/>
  <origin xyz="0.000000 0.034300 -0.000000" rpy="-0.0872514 -0.116106 0.0635088" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_index" type="fixed">
  <parent link="base"/>
  <child link="index_meta_0"/>
  <origin xyz="0.013404 0.016245 -0.018323" rpy="-3.09499 -0.222842 3.05505" />
</joint>

<joint name="in_j0" type="fixed"> <!--"continuous" -->
  <parent link="index_meta_0"/>
  <child link="index_meta"/>
  <origin xyz="-0.000000 0.075750 -0.000000" rpy="-0.118925 0.0819517 -0.100102" />
  <axis xyz="0 0 1" />
</joint>

<joint name="in_j1" type="fixed"> <!--"continuous" -->
  <parent link="index_meta"/>
  <child link="index_proximal"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="in_j2" type="fixed"> <!--"continuous" -->
  <parent link="index_proximal"/>
  <child link="index_middle"/>
  <origin xyz="0.000000 0.045655 -0.000000" rpy="-0.0306015 0.116715 -0.183591" />
  <axis xyz="1 0 0" />
</joint>

<joint name="in_j3" type="fixed"> <!--"continuous" -->
  <parent link="index_middle"/>
  <child link="index_distal"/>
  <origin xyz="0.000000 0.023888 0.000000" rpy="0.102189 -0.0180627 -0.0869717" />
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j0" type="fixed"> <!--"continuous" -->
  <parent link="base"/>
  <child link="thumb_meta_0"/>
  <origin xyz="0.024445 0.010599 -0.003052" rpy="-2.87468 0.716929 2.69534" />
  <axis xyz="0 0 1" />
</joint>

<joint name="th_j1" type="fixed"> <!--"continuous" -->
  <parent link="thumb_meta_0"/>
  <child link="thumb_meta"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j2" type="fixed"> <!--"continuous" -->
  <parent link="thumb_meta"/>
  <child link="thumb_proximal"/>
  <origin xyz="0.000000 0.050024 -0.000000" rpy="-0.711146 -0.339941 -0.0309624" />
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j3" type="fixed"> <!--"continuous" -->
  <parent link="thumb_proximal"/>
  <child link="thumb_distal"/>
  <origin xyz="0.000000 0.034977 -0.000000" rpy="-0.00830731 0.0670157 0.0352878" />
  <axis xyz="1 0 0" />
</joint>

<link name="sim_hand_palm" />

<joint name="hand_palm" type="fixed">
  <parent link="base"/>
  <child link="sim_hand_palm"/>
  <origin xyz="0 0.08 0" rpy="0 0 1.57" />
</joint>

<!-- ==== Appending a right hand ======= -->

<!-- ==== Appending a left hand ======= -->
<link name="base_0_l" />

<link name="base_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_0.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_meta_0_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_1.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_meta_l" />

<link name="pinky_proximal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_2.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_middle_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_3.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="pinky_distal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_4.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_meta_0_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_6.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_meta_l" />

<link name="ring_proximal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_7.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_middle_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_8.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="ring_distal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_9.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_meta_0_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_11.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_meta_l" />

<link name="middle_proximal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_12.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_middle_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_13.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="middle_distal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_14.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_meta_0_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_16.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_meta_l" />

<link name="index_proximal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_17.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_middle_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_18.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="index_distal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_19.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="thumb_meta_0_l" />

<link name="thumb_meta_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_21.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>  

<link name="thumb_proximal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_22.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<link name="thumb_distal_l">
  <visual>
    <geometry>
      <mesh filename="file:///home/pardon/handover_ws/src/human_detector/human_model_gazebo/asr_cyberglove_visualization/meshes/bone_1_23.dae" scale="0.001 0.001 0.001" />
    </geometry>
  </visual>
</link>

<joint name="wr_j0_l" type="fixed">
  <parent link="handleft_link"/>
  <child link="base_0_l"/>
  <origin xyz="0 0 0" rpy="1.57 0 0" />
  <axis xyz="0 0 1" />
</joint>

<joint name="wr_j1_l" type="fixed">
  <parent link="base_0_l"/>
  <child link="base_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="base_pinky_l" type="fixed">
  <parent link="base_l"/>
  <child link="pinky_meta_0_l"/>
  <origin xyz="0.024912 0.008636 0.002422" rpy="2.80824 0.811484 2.74123" />
</joint>

<joint name="pi_j0_l" type="fixed">
  <parent link="pinky_meta_0_l"/>
  <child link="pinky_meta_l"/>
  <origin xyz="0.000000 0.063265 -0.000000" rpy="0.0196487 0.191181 -0.113497" />
  <axis xyz="0 0 1" />
</joint>

<joint name="pi_j1_l" type="fixed">
  <parent link="pinky_meta_l"/>
  <child link="pinky_proximal_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="pi_j2_l" type="fixed">
  <parent link="pinky_proximal_l"/>
  <child link="pinky_middle_l"/>
  <origin xyz="0.000000 0.034557 0.000000" rpy="0.0304249 0.0981504 -0.133914" />
  <axis xyz="1 0 0" />
</joint>

<joint name="pi_j3_l" type="fixed">
  <parent link="pinky_middle_l"/>
  <child link="pinky_distal_l"/>
  <origin xyz="0.000000 0.025298 -0.000000" rpy="-0.0317568 -0.00503542 -0.0988644" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_ring_l" type="fixed">
  <parent link="base_l"/>
  <child link="ring_meta_0_l"/>
  <origin xyz="0.012468 0.014241 -0.007279" rpy="3.03476 0.620396 2.98236" />
</joint>

<joint name="ri_j0_l" type="fixed">
  <parent link="ring_meta_0_l"/>
  <child link="ring_meta_l"/>
    <origin xyz="0.000000 0.069086 -0.000000" rpy="-0.153666 0.161247 -0.0107861" />
  <axis xyz="0 0 1" />
</joint>

<joint name="ri_j1_l" type="fixed">
  <parent link="ring_meta_l"/>
  <child link="ring_proximal_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="ri_j2_l" type="fixed">
  <parent link="ring_proximal_l"/>
  <child link="ring_middle_l"/>
  <origin xyz="-0.000000 0.042662 -0.000000" rpy="0.0661994 -0.10508 0.0317381" />
  <axis xyz="1 0 0" />
</joint>

<joint name="ri_j3_l" type="fixed">
  <parent link="ring_middle_l"/>
  <child link="ring_distal_l"/>
  <origin xyz="0.000000 0.028928 0.000000" rpy="0.102201 0.0505654 -0.0213048" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_middle_l" type="fixed">
  <parent link="base_l"/>
  <child link="middle_meta_0_l"/>
  <origin xyz="-0.001406 0.015512 -0.015156" rpy="3.13273 0.39616 3.08577" />
</joint>

<joint name="mi_j0_l" type="fixed">
  <parent link="middle_meta_0_l"/>
  <child link="middle_meta_l"/>
  <origin xyz="0.000000 0.073864 -0.000000" rpy="-0.182864 -0.0762588 0.0585634" />
  <axis xyz="0 0 1" />
</joint>

<joint name="mi_j1_l" type="fixed">
  <parent link="middle_meta_l"/>
  <child link="middle_proximal_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="mi_j2_l" type="fixed">
  <parent link="middle_proximal_l"/>
  <child link="middle_middle_l"/>
  <origin xyz="0.000000 0.047566 -0.000000" rpy="0.109335 0.0553835 0.0593373" />
  <axis xyz="1 0 0" />
</joint>

<joint name="mi_j3_l" type="fixed">
  <parent link="middle_middle_l"/>
  <child link="middle_distal_l"/>
  <origin xyz="0.000000 0.034300 -0.000000" rpy="-0.0872514 0.116106 -0.0635088" />
  <axis xyz="1 0 0" />
</joint>

<joint name="base_index_l" type="fixed">
  <parent link="base_l"/>
  <child link="index_meta_0_l"/>
  <origin xyz="-0.013404 0.016245 -0.018323" rpy="-3.09499 0.222842 -3.05505" />
</joint>

<joint name="in_j0_l" type="fixed">
  <parent link="index_meta_0_l"/>
  <child link="index_meta_l"/>
  <origin xyz="-0.000000 0.075750 -0.000000" rpy="-0.118925 -0.0819517 0.100102" />
  <axis xyz="0 0 1" />
</joint>

<joint name="in_j1_l" type="fixed">
  <parent link="index_meta_l"/>
  <child link="index_proximal_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="in_j2_l" type="fixed">
  <parent link="index_proximal_l"/>
  <child link="index_middle_l"/>
  <origin xyz="0.000000 0.045655 -0.000000" rpy="-0.0306015 -0.116715 0.183591" />
  <axis xyz="1 0 0" />
</joint>

<joint name="in_j3_l" type="fixed">
  <parent link="index_middle_l"/>
  <child link="index_distal_l"/>
  <origin xyz="0.000000 0.023888 0.000000" rpy="0.102189 0.0180627 0.0869717" />
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j0_l" type="fixed">
  <parent link="base_l"/>
  <child link="thumb_meta_0_l"/>
  <origin xyz="-0.024445 0.010599 -0.003052" rpy="-2.87468 -0.716929 -2.69534" />
  <axis xyz="0 0 1" />
</joint>

<joint name="th_j1_l" type="fixed">
  <parent link="thumb_meta_0_l"/>
  <child link="thumb_meta_l"/>
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j2_l" type="fixed">
  <parent link="thumb_meta_l"/>
  <child link="thumb_proximal_l"/>
  <origin xyz="0.000000 0.050024 -0.000000" rpy="-0.711146 0.339941 0.0309624" />
  <axis xyz="1 0 0" />
</joint>

<joint name="th_j3_l" type="fixed">
  <parent link="thumb_proximal_l"/>
  <child link="thumb_distal_l"/>
  <origin xyz="0.000000 0.034977 -0.000000" rpy="-0.00830731 -0.0670157 -0.0352878" />
  <axis xyz="1 0 0" />
</joint>

<!-- ==== Appending a left hand ======= -->

<!-- ========= Appending controller to allow gazebo to actuate===== -->
<transmission name="bodyright_shoulderright_joint_tran">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="bodyright_shoulderright_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="shoulderright_armright1_joint_tran">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="shoulderright_armright1_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="armright1_armright2_joint_tran">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="armright1_armright2_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor3">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="armrighht3_handright_joint_tran">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="armrighht3_handright_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor4">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="armright2_armright3_joint_tran">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="armright2_armright3_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor5">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>


<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/human</robotNamespace>
    <legacyModeNS> false </legacyModeNS>
  </plugin>
</gazebo>

<!-- The ft_sensor plugin -->  
<!-- <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>100.0</updateRate>
        <topicName>ft_sensor_topic</topicName>
        <jointName>bodyright_shoulderright_joint</jointName>
    </plugin>
</gazebo>
 -->
<!--  ======== Appending controller ======-->



  <!-- Colour -->
  <gazebo reference="base_human_link">
    <material>Gazebo/WoodFloor</material>
  </gazebo>

  <gazebo reference="back_link">
    <material>Gazebo/WoodFloor</material>
  </gazebo>

  <gazebo reference="base_footprint">
    <material>Gazebo/Purple</material>
  </gazebo>

 
  <gazebo reference="body_link">
    <material>Gazebo/White</material>
  </gazebo>
</robot>
